### ISSUE TITLE
InvoicePlane SKU/Products 

### ISSUE THREAD

**Issue by bielenpa** [osuosl/InvoicePlane#1]
I asked for this before, ticket #28450, but here goes again. I have put the OSU fee numbers into the SKU Column of InvoicePlane Products: https://invoicing.cass.oregonstate.edu/products/index
We use those fee (SKU) numbers when creating quotes, but they do not show up in the actual quote document. I then have to print out a quote and go in and do searches of products to find the fee number and hand write it on the quote printout in order to place the quote into contract agreements. Here is a quote that I had to do this with yesterday: https://invoicing.cass.oregonstate.edu/quotes/view/61
I attached a copy of the contract where I had to re-create the wheel from the quote to put the fee numbers into Attachment A.
I am going to have to do this MANY times in the next few days in order to get the new fees in the new fiscal year agreements. 
Can this be fixed ASAP?
Thanks,
[178113AmendmentoneOSRFFY17.docx](https://github.com/osuosl/InvoicePlane/files/350795/178113AmendmentoneOSRFFY17.docx)

Pam Bielenberg
209 Milne Computer Center
Corvallis, OR 97331-5501
Pamela.Bielenberg@oregonstate.edu
Phone: 541-737-2060 Cell: 541-990-1781

**Comment by bielenpa** [comment]
@ramereth @Kennric 
What kind of timeline I can expect this to be resolved in? I first asked in April.

**Comment by ramereth** [comment]
This is being moved to osu-cass/invoiceplane-templates#32. Please update the issue there.
