### ISSUE TITLE
InvoicePlane addtl emails

### ISSUE THREAD

**Issue by bielenpa** [osuosl/InvoicePlane#2]
[support.osuosl.org #28685]
I have had requests to send invoices to two different clients in the invoicing emails. The client form does not allow for multiple emails. When I've tried using a comma or semi colon to separate they fail to send at all. 
Is it a possibility to add additional cc email fields in the "Contact Information"? https://invoicing.cass.oregonstate.edu/clients/form/131

Pam

**Comment by bielenpa** [comment]
@ramereth @Kennric 
FYI

**Comment by ramereth** [comment]
This is being moved to osu-cass/invoiceplane-templates#33. Please update the issue from there.
